#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/portweaver

start_service() {
	local enabled
	local log_enabled
	local log_file="/tmp/portweaver.log"
	config_load portweaver
	config_get_bool enabled global enabled 1
	config_get_bool log_enabled global log_enabled 1
	
	[ "$enabled" -eq 0 ] && {
		echo "PortWeaver is disabled in config"
		return 0
	}
	
	procd_open_instance

	if [ "$log_enabled" -eq 1 ]; then
		procd_append_param env PORTWEAVER_LOG_ENABLED=1
		procd_set_param command /bin/sh -c "$PROG >> $log_file 2>&1"
	else
		procd_append_param env PORTWEAVER_LOG_ENABLED=0
		procd_set_param command $PROG
	fi
	
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "portweaver"
}

reload_service() {
	restart
}
