'use strict';
'require firewall as fwmodel';
'require tools.widgets as widgets';
// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.18/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.18/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.18/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./utils/jsx-factory.ts


const JSXFragment = Symbol.for("jsx.fragment");
function filterChildren(children) {
    return children.filter((child)=>{
        if (child === null || child === undefined || typeof child === "boolean") return false;
        return true;
    });
}
function jsx_factory_createJsxElement(tag, props) {
    for(var _len = arguments.length, children = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++){
        children[_key - 2] = arguments[_key];
    }
    const filteredChildren = filterChildren(children);
    if (tag === JSXFragment) {
        const fragment = document.createDocumentFragment();
        fragment.append(...filteredChildren);
        return fragment;
    }
    if (typeof tag === "function") return tag(_object_spread_props(_object_spread({}, props), {
        children: filteredChildren
    }));
    if (props) {
        for (const [key, value] of Object.entries(props))if (typeof value === "boolean") {
            if (value) props[key] = key;
            else delete props[key];
        }
    }
    if (props === null) props = {};
    if (filteredChildren.length > 1) return E(tag, props, filteredChildren);
    else return E(tag, props, filteredChildren[0]);
}
jsx_factory_createJsxElement.Fragment = JSXFragment;
globalThis.createJsxElement = jsx_factory_createJsxElement;

;// CONCATENATED MODULE: ./utils/formatters.ts
function formatBytes() {
    let bytes = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : 0;
    if (bytes < 1024) return "".concat(bytes, " B");
    if (bytes < 1048576) return "".concat((bytes / 1024).toFixed(2), " KiB");
    if (bytes < 1073741824) return "".concat((bytes / 1048576).toFixed(2), " MiB");
    return "".concat((bytes / 1073741824).toFixed(2), " GiB");
}
function formatUptime() {
    let seconds = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : 0;
    const days = Math.floor(seconds / 86400);
    const hours = Math.floor(seconds % 86400 / 3600);
    const mins = Math.floor(seconds % 3600 / 60);
    const sec = seconds % 60;
    if (days > 0) return "".concat(days, "d ").concat(hours, "h");
    if (hours > 0) return "".concat(hours, "h ").concat(mins, "m");
    return "".concat(mins, "m").concat(sec, "s");
}
function getErrorMessage(error_code) {
    if (error_code === undefined || error_code === 0) return null;
    const messages = {
        "0": "OK",
        "-1": "Memory allocation failed",
        "-2": "Failed to bind to port",
        "-3": "Address or port already in use (EADDRINUSE)",
        "-4": "Permission denied - unable to bind to port (EACCES)",
        "-5": "Invalid address format",
        "-98": "Address already in use",
        "-91": "Protocol wrong type for socket",
        "-92": "Protocol not available",
        "-93": "Protocol not supported",
        "-94": "Socket type not supported",
        "-95": "Operation not supported on transport endpoint",
        "-96": "Protocol family not supported",
        "-97": "Address family not supported by protocol",
        "-99": "Cannot assign requested address",
        "-100": "Network is down",
        "-101": "Network is unreachable"
    };
    return messages[String(error_code)] || "Unknown error (code: ".concat(error_code, ")");
}

;// CONCATENATED MODULE: ./utils/rpc-client.ts
function createRpcClient(rpc) {
    const getStatus = rpc.declare({
        object: "portweaver",
        method: "get_status",
        expect: {}
    });
    const listProjects = rpc.declare({
        object: "portweaver",
        method: "list_projects",
        expect: {}
    });
    const setEnabled = rpc.declare({
        object: "portweaver",
        method: "set_enabled",
        params: [
            "id",
            "enabled"
        ],
        expect: {}
    });
    const getFrpStatus = rpc.declare({
        object: "portweaver",
        method: "get_frp_status",
        expect: {}
    });
    const getFrpInfo = rpc.declare({
        object: "portweaver",
        method: "get_frp_info",
        params: [
            "id"
        ],
        expect: {}
    });
    const clearFrpLogs = rpc.declare({
        object: "portweaver",
        method: "clear_frp_logs",
        params: [
            "id"
        ],
        expect: {}
    });
    const getEvents = rpc.declare({
        object: "portweaver",
        method: "get_events",
        expect: {}
    });
    return {
        getStatus,
        listProjects,
        setEnabled,
        getFrpStatus,
        getFrpInfo,
        clearFrpLogs,
        getEvents
    };
}

;// CONCATENATED MODULE: ./modules/client.tsx



const rpcClient = createRpcClient(L.rpc);
class Client {
    getProjectIndex(section_id) {
        const sections = L.uci.sections("portweaver", "project");
        for(let i = 0; i < sections.length; i++){
            if (sections[i][".name"] === section_id) return i;
        }
        return -1;
    }
    getProjectStatus(section_id) {
        const idx = this.getProjectIndex(section_id);
        return idx >= 0 && this.projectStatuses && this.projectStatuses[idx] ? this.projectStatuses[idx] : null;
    }
    renderStatusElements(status, _section_id) {
        if (!status) return [
            /*#__PURE__*/ createJsxElement("span", {
                style: "color: gray;"
            }, _("N/A"))
        ];
        const startupFailed = status.startup_status === "failed";
        const statusColor = status.status === "running" && !startupFailed ? "green" : "#dc3545";
        let errorMessage = null;
        if (startupFailed && status.error_code !== undefined && status.error_code !== 0) errorMessage = getErrorMessage(status.error_code);
        const statusBadgeAttrs = {
            class: "ifacebadge",
            style: ""
        };
        if (errorMessage) {
            statusBadgeAttrs.title = errorMessage;
            statusBadgeAttrs.style += " cursor: help;";
        }
        const statusElements = [
            /*#__PURE__*/ createJsxElement("div", null, /*#__PURE__*/ createJsxElement("span", statusBadgeAttrs, /*#__PURE__*/ createJsxElement("strong", {
                style: "font-size: 1em; font-weight: 600; color: " + statusColor + ";"
            }, startupFailed ? "failed" : status.status || "unknown")))
        ];
        if (errorMessage && status.status !== "stopped") statusElements.push(/*#__PURE__*/ createJsxElement("small", {
            style: "color: #dc3545; margin-top: 0.3em;"
        }, "\u26A0 ".concat(errorMessage)));
        else {
            const elements = [];
            if ((status.active_ports || 0) > 0) elements.push(/*#__PURE__*/ createJsxElement("span", null, _("Ports: ") + (status.active_ports || 0)));
            if (status.bytes_in || 0 || status.bytes_out || 0) {
                if (elements.length > 0) elements.push(/*#__PURE__*/ createJsxElement("br", null));
                elements.push(/*#__PURE__*/ createJsxElement("span", null, "\u2193 " + formatBytes(status.bytes_in || 0) + " \u2191 " + formatBytes(status.bytes_out || 0)));
            }
            if (status.forwarders && status.forwarders.length > 0) {
                if (elements.length > 0) elements.push(/*#__PURE__*/ createJsxElement("br", null));
                elements.push(this.renderForwarderStats(status.forwarders));
            }
            if (elements.length > 0) statusElements.push(/*#__PURE__*/ createJsxElement("small", null, elements));
        }
        return statusElements;
    }
    renderForwarderStats(forwarders) {
        const rows = forwarders.map((f)=>/*#__PURE__*/ createJsxElement("div", {
                style: "display: flex; gap: 0.5em; padding: 0.15em 0; font-size: 0.9em; border-bottom: 1px solid #eee;"
            }, /*#__PURE__*/ createJsxElement("span", {
                style: "min-width: 35px; color: #6c757d;"
            }, f.protocol.toUpperCase()), /*#__PURE__*/ createJsxElement("span", {
                style: "min-width: 45px;"
            }, ":", f.local_port), /*#__PURE__*/ createJsxElement("span", {
                style: "color: #28a745;"
            }, "\u2193" + formatBytes(f.bytes_in)), /*#__PURE__*/ createJsxElement("span", {
                style: "color: #dc3545;"
            }, "\u2191" + formatBytes(f.bytes_out))));
        return /*#__PURE__*/ createJsxElement("div", {
            style: "margin-top: 0.3em; padding: 0.3em; background: #f8f9fa; border-radius: 3px; max-height: 80px; overflow-y: auto;"
        }, rows);
    }
    updateProjectHealthIndicator() {
        var _this_projectStatuses;
        const enabledProjects = ((_this_projectStatuses = this.projectStatuses) === null || _this_projectStatuses === void 0 ? void 0 : _this_projectStatuses.filter((p)=>p.enabled)) || [];
        const runningProjects = enabledProjects.filter((p)=>p.status === "running");
        const healthElem = document.getElementById("project-health-value");
        if (healthElem) {
            const healthColor = runningProjects.length === enabledProjects.length ? "#28a745" : runningProjects.length > 0 ? "#ffc107" : "#dc3545";
            healthElem.innerHTML = "";
            healthElem.appendChild(/*#__PURE__*/ createJsxElement("span", null, /*#__PURE__*/ createJsxElement("strong", {
                style: "font-size: 1.1em; font-weight: 600; color: ".concat(healthColor, ";")
            }, runningProjects.length, " / ", enabledProjects.length), /*#__PURE__*/ createJsxElement("div", {
                style: "font-size: 0.85em; color: #6c757d; margin-top: 0.3em;"
            }, _("projects running"))));
        }
    }
    updateFrpErrorDisplay() {
        const errorElem = document.getElementById("frp-error-value");
        if (errorElem && this.frpStatus.last_error) {
            const truncated = this.frpStatus.last_error.length > 50 ? this.frpStatus.last_error.substring(0, 47) + "..." : this.frpStatus.last_error;
            errorElem.title = this.frpStatus.last_error;
            errorElem.innerHTML = "";
            errorElem.appendChild(/*#__PURE__*/ createJsxElement("strong", {
                style: "font-size: 0.95em; font-weight: 600; color: #dc3545;"
            }, truncated));
        }
    }
    updateActivityLog() {
        const logContainer = document.getElementById("activity-log-container");
        if (logContainer && this.events && this.events.length > 0) {
            const recentEvents = this.events.slice(-5).reverse();
            logContainer.innerHTML = "";
            for (const event of recentEvents)logContainer.appendChild(this.renderEventRow(event));
        }
    }
    renderEventRow(event) {
        const eventColors = {
            project_started: "#28a745",
            project_stopped: "#6c757d",
            frp_error: "#dc3545",
            frp_connected: "#28a745",
            frp_disconnected: "#ffc107",
            config_changed: "#17a2b8"
        };
        const eventIcons = {
            project_started: "\u25B6",
            project_stopped: "\u23F9",
            frp_error: "\u26A0",
            frp_connected: "\uD83D\uDD17",
            frp_disconnected: "\uD83D\uDD0C",
            config_changed: "\u2699"
        };
        const color = eventColors[event.type] || "#6c757d";
        const icon = eventIcons[event.type] || "\u2022";
        const time = this.formatTimestamp(event.timestamp);
        const truncatedMessage = event.message.length > 60 ? event.message.substring(0, 57) + "..." : event.message;
        return /*#__PURE__*/ createJsxElement("div", {
            style: "display: flex; align-items: flex-start; padding: 0.3em 0; border-bottom: 1px solid #eee; font-size: 0.85em;"
        }, /*#__PURE__*/ createJsxElement("span", {
            style: "color: ".concat(color, "; margin-right: 0.5em; flex-shrink: 0;")
        }, icon), /*#__PURE__*/ createJsxElement("span", {
            style: "color: #6c757d; margin-right: 0.5em; flex-shrink: 0; min-width: 70px;"
        }, time), /*#__PURE__*/ createJsxElement("span", {
            style: "flex: 1; word-break: break-word;",
            title: event.message
        }, truncatedMessage));
    }
    formatTimestamp(timestamp) {
        const date = new Date(timestamp);
        const hours = date.getHours().toString().padStart(2, "0");
        const minutes = date.getMinutes().toString().padStart(2, "0");
        const seconds = date.getSeconds().toString().padStart(2, "0");
        return "".concat(hours, ":").concat(minutes, ":").concat(seconds);
    }
    constructor(data){
        _define_property(this, "globalStatus", void 0);
        _define_property(this, "projectStatuses", void 0);
        _define_property(this, "frpStatus", void 0);
        _define_property(this, "events", void 0);
        this.globalStatus = data[0] || {};
        this.projectStatuses = data[1] ? data[1].projects || [] : [];
        this.frpStatus = data[2] || {
            frp_enabled: false
        };
        this.events = data[3] || [];
        L.Poll.add(async ()=>{
            const updateText = (id, value)=>{
                const elem = document.getElementById(id);
                if (elem) elem.textContent = String(value);
            };
            try {
                var _results_, _results_1;
                const results = await Promise.all([
                    rpcClient.getStatus(),
                    rpcClient.listProjects(),
                    rpcClient.getFrpStatus(),
                    rpcClient.getEvents()
                ]);
                this.globalStatus = results[0] || {};
                this.projectStatuses = ((_results_ = results[1]) === null || _results_ === void 0 ? void 0 : _results_.projects) ? results[1].projects : [];
                this.frpStatus = results[2] || {
                    frp_enabled: false
                };
                this.events = ((_results_1 = results[3]) === null || _results_1 === void 0 ? void 0 : _results_1.events) || [];
                const statusElem = document.getElementById("status-value");
                const statusColors = {
                    running: "green",
                    stopped: "red",
                    degraded: "orange"
                };
                if (statusElem) {
                    statusElem.textContent = this.globalStatus.status || "-";
                    statusElem.style.color = statusColors[this.globalStatus.status || ""] || "gray";
                }
                updateText("total-projects-value", this.globalStatus.total_projects || 0);
                updateText("active-ports-value", this.globalStatus.active_ports || 0);
                updateText("uptime-value", formatUptime(this.globalStatus.uptime || 0));
                updateText("traffic-in-value", formatBytes(this.globalStatus.total_bytes_in || 0));
                updateText("traffic-out-value", formatBytes(this.globalStatus.total_bytes_out || 0));
                const frpEnabledElem = document.getElementById("frp-enabled-value");
                if (frpEnabledElem) {
                    frpEnabledElem.textContent = this.frpStatus.frp_enabled ? _("Enabled") : _("Disabled");
                    frpEnabledElem.style.color = this.frpStatus.frp_enabled ? "#28a745" : "#6c757d";
                }
                const frpVersionElem = document.getElementById("frp-version-value");
                if (frpVersionElem && this.frpStatus.frp_version) frpVersionElem.textContent = this.frpStatus.frp_version;
                this.updateProjectHealthIndicator();
                this.updateFrpErrorDisplay();
                this.updateActivityLog();
                (()=>{
                    const sections = L.uci.sections("portweaver", "project") || [];
                    for(let i = 0; i < sections.length; i++){
                        const section_id = sections[i][".name"];
                        if (!section_id) continue;
                        const status = this.getProjectStatus(section_id);
                        const section = document.getElementById("project-status-".concat(section_id));
                        if (!section) continue;
                        const newStatusElements = this.renderStatusElements(status, section_id);
                        section.replaceWith(/*#__PURE__*/ createJsxElement("span", null, /*#__PURE__*/ createJsxElement("div", {
                            id: "project-status-".concat(section_id)
                        }, newStatusElements)));
                    }
                })();
            } catch (err) {
                console.warn("Auto-refresh failed:", err);
            }
        }, 3);
    }
}

;// CONCATENATED MODULE: ./components/LogViewer.tsx


class LogViewer {
    render() {
        const statusColor = {
            connected: "#4CAF50",
            connecting: "#FFC107",
            error: "#F44336",
            stopped: "#9E9E9E",
            unavailable: "#9E9E9E"
        }[this.status] || "#9E9E9E";
        return /*#__PURE__*/ createJsxElement("div", {
            style: "position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000;",
            onclick: (e)=>{
                if (e.target === e.currentTarget) this.close();
            }
        }, /*#__PURE__*/ createJsxElement("div", {
            style: "background: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); width: 90%; max-width: 800px; max-height: 80vh; display: flex; flex-direction: column;"
        }, /*#__PURE__*/ createJsxElement("div", {
            style: "padding: 1.5em; border-bottom: 1px solid #dee2e6; display: flex; justify-content: space-between; align-items: center;"
        }, /*#__PURE__*/ createJsxElement("div", null, /*#__PURE__*/ createJsxElement("h3", {
            style: "margin: 0; font-size: 1.2em; font-weight: 600;"
        }, "FRP Client Logs"), /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.85em; color: #6c757d; margin-top: 0.3em;"
        }, "Status:", " ", /*#__PURE__*/ createJsxElement("span", {
            style: "color: ".concat(statusColor, "; font-weight: 600;")
        }, this.status), this.lastError && /*#__PURE__*/ createJsxElement("div", {
            style: "color: #F44336; margin-top: 0.3em;"
        }, "Error: ", this.lastError))), /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            onclick: ()=>this.close(),
            style: "background: none; border: none; font-size: 1.5em; cursor: pointer; color: #6c757d;"
        }, "\xd7")), /*#__PURE__*/ createJsxElement("div", {
            style: "flex: 1; overflow-y: auto; padding: 1em; background: #f8f9fa; font-family: monospace; font-size: 0.85em; line-height: 1.5;",
            id: "logs-container-".concat(this.projectId)
        }, this.logs.length === 0 ? /*#__PURE__*/ createJsxElement("div", {
            style: "color: #6c757d; text-align: center; padding: 2em;"
        }, "No logs available") : this.logs.map((log)=>/*#__PURE__*/ createJsxElement("div", {
                style: "color: #333; word-break: break-word;"
            }, log))), /*#__PURE__*/ createJsxElement("div", {
            style: "padding: 1em; border-top: 1px solid #dee2e6; display: flex; gap: 0.5em; justify-content: flex-end;"
        }, /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            onclick: ()=>this.copyToClipboard(),
            style: "padding: 0.5em 1em; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.9em;"
        }, "Copy to Clipboard"), /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            onclick: ()=>this.clearLogs(),
            style: "padding: 0.5em 1em; background: #dc3545; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.9em;"
        }, "Clear Logs"), /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            onclick: ()=>this.close(),
            style: "padding: 0.5em 1em; background: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.9em;"
        }, "Close"))));
    }
    open() {
        this.isOpen = true;
        this.startPolling();
        document.body.appendChild(this.render());
    }
    close() {
        var _document_querySelector;
        this.isOpen = false;
        this.stopPolling();
        const modal = (_document_querySelector = document.querySelector('[id^="logs-container-'.concat(this.projectId, '"]'))) === null || _document_querySelector === void 0 ? void 0 : _document_querySelector.closest("div");
        if (modal === null || modal === void 0 ? void 0 : modal.parentElement) modal.parentElement.removeChild(modal);
    }
    startPolling() {
        this.fetchLogs();
        this.pollInterval = setInterval(()=>{
            if (this.isOpen) this.fetchLogs();
        }, 3000);
    }
    stopPolling() {
        if (this.pollInterval) {
            clearInterval(this.pollInterval);
            this.pollInterval = null;
        }
    }
    fetchLogs() {
        rpcClient.getFrpInfo(String(this.projectId)).then((response)=>{
            this.status = response.status || "unavailable";
            this.lastError = response.last_error || "";
            this.logs = response.logs || [];
            this.updateDisplay();
        }).catch((err)=>{
            console.error("Failed to fetch FRP logs:", err);
            this.status = "error";
            this.lastError = "Failed to fetch logs";
        });
    }
    updateDisplay() {
        const container = document.getElementById("logs-container-".concat(this.projectId));
        if (container) {
            container.innerHTML = "";
            if (this.logs.length === 0) container.innerHTML = '<div style="color: #6c757d; text-align: center; padding: 2em;">No logs available</div>';
            else this.logs.forEach((log)=>{
                const logEl = document.createElement("div");
                logEl.style.cssText = "color: #333; word-break: break-word; margin-bottom: 0.2em;";
                logEl.textContent = log;
                container.appendChild(logEl);
            });
            container.scrollTop = container.scrollHeight;
        }
    }
    copyToClipboard() {
        const text = this.logs.join("\n");
        navigator.clipboard.writeText(text).then(()=>{
            alert("Logs copied to clipboard");
        }).catch((err)=>{
            console.error("Failed to copy logs:", err);
            alert("Failed to copy logs");
        });
    }
    clearLogs() {
        if (confirm("Are you sure you want to clear the logs?")) rpcClient.clearFrpLogs(String(this.projectId)).then(()=>{
            this.logs = [];
            this.updateDisplay();
        }).catch((err)=>{
            console.error("Failed to clear logs:", err);
            alert("Failed to clear logs");
        });
    }
    constructor(projectId){
        _define_property(this, "projectId", void 0);
        _define_property(this, "isOpen", false);
        _define_property(this, "pollInterval", null);
        _define_property(this, "logs", []);
        _define_property(this, "status", "unavailable");
        _define_property(this, "lastError", "");
        this.projectId = projectId;
    }
}

;// CONCATENATED MODULE: ./modules/frp.tsx


const frp_form = L.form;
const nodeStatuses = {};
const frp_statusElements = {};
const actionButtons = {};
/* export default */ function frp(m, s, tab_id) {
    let o;
    o = s.taboption(tab_id, frp_form.SectionValue, "_frp_nodes", frp_form.GridSection, "frp_node");
    const ss = o.subsection;
    ss.anonymous = true;
    ss.addremove = true;
    ss.sortable = true;
    ss.cloneable = true;
    ss.sectiontitle = (section_id)=>L.uci.get("portweaver", section_id, "name") || section_id || _("Unnamed node");
    o = ss.option(frp_form.Value, "name", _("Node Name"));
    o.modalonly = true;
    o.rmempty = false;
    o.datatype = "string";
    o.placeholder = "node1";
    o.validate = (_section_id, value)=>{
        if (!value || String(value).trim() === "") return _("Node name is required");
        if (!/^[a-zA-Z0-9_-]+$/.test(String(value).trim())) return _("Node name must contain only alphanumeric characters, underscore, or hyphen");
        return true;
    };
    o = ss.option(frp_form.DummyValue, "status", _("Status"));
    o.modalonly = false;
    o.textvalue = (section_id)=>{
        const info = nodeStatuses[section_id] || {
            status: "unavailable"
        };
        const statusColor = {
            connected: "#4CAF50",
            connecting: "#FFC107",
            error: "#F44336",
            stopped: "#9E9E9E",
            unavailable: "#9E9E9E"
        }[info.status] || "#9E9E9E";
        const statusText = {
            connected: _("Connected"),
            connecting: _("Connecting"),
            error: _("Error"),
            stopped: _("Stopped"),
            unavailable: _("Unavailable")
        }[info.status] || info.status;
        const indicator = /*#__PURE__*/ createJsxElement("span", {
            style: "display:inline-block; width:12px; height:12px; border-radius:50%; background-color:".concat(statusColor, "; margin-right:8px;")
        });
        const textSpan = /*#__PURE__*/ createJsxElement("span", null, statusText);
        const container = /*#__PURE__*/ createJsxElement("span", {
            style: "display:flex; align-items:center;"
        });
        container.appendChild(indicator);
        container.appendChild(textSpan);
        frp_statusElements[section_id] = container;
        return container;
    };
    o = ss.option(frp_form.Value, "server", _("FRP Server Address"));
    o.modalonly = true;
    o.rmempty = false;
    o.datatype = "host";
    o.placeholder = "1.2.3.4";
    o.validate = (_section_id, value)=>{
        if (!value || String(value).trim() === "") return _("Server address is required");
        return true;
    };
    o = ss.option(frp_form.Value, "port", _("FRP Server Port"));
    o.modalonly = true;
    o.rmempty = false;
    o.datatype = "port";
    o.placeholder = "7000";
    o.validate = (_section_id, value)=>{
        if (!value || String(value).trim() === "") return _("Server port is required");
        const port = parseInt(value, 10);
        if (Number.isNaN(port) || port < 1 || port > 65535) return _("Port must be between 1 and 65535");
        return true;
    };
    o = ss.option(frp_form.Value, "token", _("Authentication Token"));
    o.modalonly = true;
    o.password = true;
    o.rmempty = true;
    o.placeholder = "optional token for authentication";
    o = ss.option(frp_form.DummyValue, "actions", _("Actions"));
    o.modalonly = false;
    o.textvalue = (section_id)=>{
        var _nodeStatuses_section_id;
        const isRunning = (((_nodeStatuses_section_id = nodeStatuses[section_id]) === null || _nodeStatuses_section_id === void 0 ? void 0 : _nodeStatuses_section_id.status) || "stopped") !== "stopped";
        const btn = /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            class: "cbi-button cbi-button-action",
            onclick: ()=>{
                const logViewer = new LogViewer(parseInt(section_id, 10));
                logViewer.open();
            },
            disabled: !isRunning
        }, _("View Logs"));
        actionButtons[section_id] = btn;
        return btn;
    };
    L.Poll.add(async ()=>{
        try {
            const sections = await L.uci.sections("portweaver", "frp_node");
            const promises = sections.map((sec)=>rpcClient.getFrpInfo(sec[".name"]).then((res)=>{
                    var _nodeStatuses_sec_name;
                    const oldStatus = (_nodeStatuses_sec_name = nodeStatuses[sec[".name"]]) === null || _nodeStatuses_sec_name === void 0 ? void 0 : _nodeStatuses_sec_name.status;
                    nodeStatuses[sec[".name"]] = res;
                    if (oldStatus !== res.status) {
                        const container = frp_statusElements[sec[".name"]];
                        if (container && container.childNodes.length >= 2) {
                            const indicator = container.childNodes[0];
                            const textSpan = container.childNodes[1];
                            const statusColor = {
                                connected: "#4CAF50",
                                connecting: "#FFC107",
                                error: "#F44336",
                                stopped: "#9E9E9E",
                                unavailable: "#9E9E9E"
                            }[res.status] || "#9E9E9E";
                            indicator.style.backgroundColor = statusColor;
                            const statusText = {
                                connected: _("Connected"),
                                connecting: _("Connecting"),
                                error: _("Error"),
                                stopped: _("Stopped"),
                                unavailable: _("Unavailable")
                            }[res.status] || res.status;
                            textSpan.textContent = statusText;
                        }
                        const actionBtn = actionButtons[sec[".name"]];
                        if (actionBtn) {
                            const isRunning = res.status !== "stopped";
                            actionBtn.disabled = !isRunning;
                        }
                    }
                }).catch(()=>{
                    nodeStatuses[sec[".name"]] = {
                        status: "error",
                        last_error: "Failed to fetch status"
                    };
                    const container = frp_statusElements[sec[".name"]];
                    if (container && container.childNodes.length >= 2) {
                        const indicator = container.childNodes[0];
                        const textSpan = container.childNodes[1];
                        indicator.style.backgroundColor = "#F44336";
                        textSpan.textContent = _("Error");
                    }
                    const actionBtn = actionButtons[sec[".name"]];
                    if (actionBtn) actionBtn.disabled = true;
                }));
            await Promise.all(promises);
        } catch (e) {
            console.error("Polling for FRP status failed:", e);
        }
    }, 5);
}

;// CONCATENATED MODULE: ./components/ValidatedInput.tsx

/**
 * 创建带验证的通用 input 元素
 * @param options 配置选项
 * @returns 返回 input 元素
 */ function ValidatedInput(options) {
    const { type = "text", className = "", value = "", placeholder = "", style = "", disabled = false, onValidate, dataAttributes = {}, validateOn = "both" } = options;
    const dataAttrs = {};
    Object.entries(dataAttributes).forEach((param)=>{
        let [key, val] = param;
        dataAttrs["data-".concat(key)] = val;
    });
    const input = /*#__PURE__*/ createJsxElement("input", _object_spread({
        type: type,
        class: className,
        value: value,
        placeholder: placeholder,
        style: style,
        disabled: disabled
    }, dataAttrs));
    const validate = ()=>{
        if (onValidate) {
            const isValid = onValidate(input.value.trim());
            if (!isValid) input.style.setProperty("border-color", "red", "important");
            else input.style.borderColor = "";
        }
    };
    const clearValidation = ()=>{
        input.style.borderColor = "";
    };
    if (validateOn === "input") input.addEventListener("input", validate);
    else if (validateOn === "blur") {
        input.addEventListener("input", clearValidation);
        input.addEventListener("blur", validate);
    } else if (validateOn === "change") input.addEventListener("change", validate);
    else if (validateOn === "both") {
        input.addEventListener("input", validate);
        input.addEventListener("change", validate);
    }
    return input;
}

;// CONCATENATED MODULE: ./components/FrpNodeSelector.tsx


/**
 * 创建可复用的 FRP 节点选择器 UI
 * @param options 配置选项
 * @returns 返回容器元素和选中节点的 getter 函数
 */ function createFrpNodeSelector(options) {
    const { selectedNodes, onChange, checkboxClass = "frp-node-checkbox", portInputClass = "frp-node-port", containerStyle } = options;
    const frp_sections = L.uci.sections("portweaver", "frp_node") || [];
    const node_map = {};
    // 解析已选择的节点
    for (const item of selectedNodes){
        const parts = item.split(":");
        const node = parts[0];
        const port = parts[1] || "";
        node_map[node] = port;
    }
    const checkboxes = [];
    const portInputs = new Map();
    const updateHandler = ()=>{
        const values = [];
        for (const cb of checkboxes)if (cb.checked) {
            const node = cb.getAttribute("data-node");
            const port_inp = portInputs.get(node);
            const port = port_inp ? port_inp.value.trim() : "";
            if (port) values.push("".concat(node, ":").concat(port));
            else values.push(node);
        }
        if (onChange) onChange(values);
    };
    const container = /*#__PURE__*/ createJsxElement("div", {
        style: containerStyle || ""
    });
    if (frp_sections.length === 0) {
        const emptyMsg = _("No FRP nodes configured");
        container.appendChild(/*#__PURE__*/ createJsxElement("em", {
            style: "color: #999;"
        }, emptyMsg));
    } else {
        const table = /*#__PURE__*/ createJsxElement("table", {
            class: "table",
            style: "margin: 0; width: auto;"
        });
        for (const frp_section of frp_sections){
            const node_name = String(frp_section.name || frp_section[".name"]);
            if (!node_name) continue;
            const is_checked = Object.hasOwn(node_map, node_name);
            const port_value = node_map[node_name] || "";
            const checkbox = /*#__PURE__*/ createJsxElement("input", {
                type: "checkbox",
                class: checkboxClass,
                "data-node": node_name,
                checked: is_checked,
                style: "margin-right: 8px;"
            });
            const port_input = /*#__PURE__*/ createJsxElement(ValidatedInput, {
                type: "text",
                className: portInputClass,
                value: port_value,
                placeholder: _("default port"),
                style: "min-width: 100px !important; width: calc(100% - 80px) !important; margin-left: 10px;",
                disabled: !is_checked,
                dataAttributes: {
                    node: node_name
                },
                onValidate: (value)=>{
                    if (!value) return true; // 空值视为有效
                    const p = parseInt(value, 10);
                    return !Number.isNaN(p) && p >= 1 && p <= 65535;
                }
            });
            checkboxes.push(checkbox);
            portInputs.set(node_name, port_input);
            const port_input_area = /*#__PURE__*/ createJsxElement("td", {
                style: "padding: 4px 8px; border: none;".concat(is_checked ? "" : "display: none;")
            }, /*#__PURE__*/ createJsxElement("span", {
                style: "margin-right: 5px; color: #666;"
            }, _("Port:")), port_input);
            checkbox.addEventListener("change", (ev)=>{
                const element = ev.currentTarget;
                port_input.disabled = !element.checked;
                port_input_area.style.display = element.checked ? "" : "none";
                if (!element.checked) port_input.value = "";
                updateHandler();
            });
            port_input.addEventListener("change", updateHandler);
            const row = /*#__PURE__*/ createJsxElement("tr", null, /*#__PURE__*/ createJsxElement("td", {
                style: "padding: 4px 8px; border: none;"
            }, checkbox, /*#__PURE__*/ createJsxElement("span", {
                style: "cursor: pointer; font-weight: normal; margin: 0;"
            }, node_name)), port_input_area);
            table.appendChild(row);
        }
        container.appendChild(table);
    }
    // 验证逻辑
    let validationError = "";
    let isValidFlag = true;
    const validate = (value)=>{
        // 验证值的格式：应该是空或空格分隔的 "node:port" 对
        if (!value) {
            validationError = "";
            isValidFlag = true;
            return;
        }
        const valueStr = Array.isArray(value) ? value.join(" ") : String(value);
        const parts = valueStr.split(/\s+/).filter(Boolean);
        for (const part of parts){
            const [node, port] = part.split(":");
            // 检查节点名称是否为空
            if (!node) {
                validationError = _("Invalid FRP node format");
                isValidFlag = false;
                return;
            }
            // 如果指定了端口，验证端口号
            if (port) {
                const portNum = parseInt(port, 10);
                if (Number.isNaN(portNum) || portNum < 1 || portNum > 65535) {
                    validationError = _("Port must be a number between 1 and 65535");
                    isValidFlag = false;
                    return;
                }
            }
        }
        validationError = "";
        isValidFlag = true;
    };
    // 返回容器和获取当前选中节点的函数
    return {
        container,
        getSelectedNodes: ()=>{
            const values = [];
            for (const cb of checkboxes)if (cb.checked) {
                const node = cb.getAttribute("data-node");
                const port_inp = portInputs.get(node);
                const port = port_inp ? port_inp.value.trim() : "";
                values.push(port ? "".concat(node, ":").concat(port) : node);
            }
            return values;
        },
        isValid: ()=>{
            const nodes = [];
            for (const cb of checkboxes)if (cb.checked) {
                const node = cb.getAttribute("data-node");
                const port_inp = portInputs.get(node);
                const port = port_inp ? port_inp.value.trim() : "";
                nodes.push(port ? "".concat(node, ":").concat(port) : node);
            }
            validate(nodes);
            return isValidFlag;
        },
        getValidationError: ()=>{
            return validationError || "";
        }
    };
}
class FrpNodeSelector extends L.form.Value {
    renderWidget(section_id, _option_index, cfgvalue) {
        const current_value = Array.isArray(cfgvalue) ? cfgvalue : typeof cfgvalue === "string" ? String(cfgvalue).split(/\s+/).filter(Boolean) : [];
        const widget_id = this.cbid(section_id);
        let hiddenInput;
        const selector = createFrpNodeSelector({
            selectedNodes: current_value,
            onChange: (nodes)=>{
                hiddenInput.value = nodes.join(" ");
            },
            checkboxClass: "frp-node-checkbox",
            portInputClass: "frp-node-port"
        });
        const { container: selectorContainer } = selector;
        // 保存验证函数引用
        this.selectorValidation = {
            isValid: selector.isValid,
            getValidationError: selector.getValidationError
        };
        hiddenInput = /*#__PURE__*/ createJsxElement("input", {
            type: "hidden",
            id: widget_id,
            name: widget_id,
            value: current_value.join(" ")
        });
        const container = /*#__PURE__*/ createJsxElement("div", {
            class: "cbi-value-field"
        });
        container.appendChild(selectorContainer);
        container.appendChild(hiddenInput);
        // 存储 hiddenInput 引用供 formvalue 方法使用
        this.hiddenInput = hiddenInput;
        const description = /*#__PURE__*/ createJsxElement("div", {
            class: "cbi-value-description"
        }, _("Select FRP nodes and optionally specify custom ports. Leave port empty to use default."));
        container.appendChild(description);
        return container;
    }
    cfgvalue(section_id) {
        const value = L.uci.get("portweaver", section_id, "frp_nodes");
        if (Array.isArray(value)) return value;
        if (typeof value === "string") return String(value).split(/\s+/).filter(Boolean);
        return [];
    }
    isChanged(section_id) {
        let cfg = this.cfgvalue(section_id);
        let form = this.formvalue(section_id);
        if (!Array.isArray(cfg)) cfg = [];
        if (!Array.isArray(form)) form = [];
        if (cfg.length !== form.length) return true;
        for(let i = 0; i < cfg.length; i++){
            if (cfg[i] !== form[i]) return true;
        }
        return false;
    }
    formvalue(_section_id) {
        if (this.hiddenInput) {
            const result = this.hiddenInput.value.split(/\s+/).filter(Boolean);
            return result.length > 0 ? result : [];
        }
        return [];
    }
    write(section_id, formvalue) {
        if (formvalue && formvalue.length > 0) return L.uci.set("portweaver", section_id, "frp_nodes", formvalue);
        else return L.uci.unset("portweaver", section_id, "frp_nodes");
    }
    isValid(_section_id) {
        // 复用 createFrpNodeSelector 中的验证逻辑
        if (this.selectorValidation) return this.selectorValidation.isValid();
        return true;
    }
    getValidationError(_section_id) {
        // 复用 createFrpNodeSelector 中的验证逻辑
        if (this.selectorValidation && !this.selectorValidation.isValid()) return this.selectorValidation.getValidationError() || _("Validation failed");
        return "";
    }
    constructor(...args){
        super(...args), _define_property(this, "hiddenInput", void 0), _define_property(this, "selectorValidation", void 0);
    }
}
/* export default */ const components_FrpNodeSelector = (FrpNodeSelector);

;// CONCATENATED MODULE: ./components/PortMappingEditor.tsx



class PortMappingEditor extends L.form.Value {
    parseMapping(str) {
        if (!str || typeof str !== "string") return null;
        str = str.trim();
        const mapping = {
            listenPort: "",
            targetPort: "",
            frpNodes: [],
            protocol: "tcp"
        };
        const protocolMatch = str.match(/\/([a-z]+)$/);
        if (protocolMatch) {
            mapping.protocol = protocolMatch[1].toLowerCase();
            str = str.substring(0, protocolMatch.index);
        }
        let i = 0;
        while(str[i] === "["){
            const end = str.indexOf("]", i);
            if (end === -1) break;
            const content = str.substring(i + 1, end);
            if (content.indexOf(":") !== -1 || /[a-zA-Z_-]/.test(content)) {
                mapping.frpNodes.push(content);
                i = end + 1;
                continue;
            }
            if (content.match(/^\d+(?:-\d+)?$/)) {
                mapping.listenPort = content;
                i = end + 1;
                break;
            }
            break;
        }
        const rest = str.substring(i);
        if (!mapping.listenPort) {
            const parts0 = rest.split(":");
            if (parts0.length >= 1) mapping.listenPort = parts0[0].trim().replace(/[[\]]/g, "");
            if (parts0.length >= 2) mapping.targetPort = parts0[1].trim().replace(/[[\]]/g, "");
        } else if (rest.startsWith(":")) mapping.targetPort = rest.substring(1).trim().replace(/[[\]]/g, "");
        return mapping;
    }
    buildString(mapping) {
        let result = "";
        if (mapping.frpNodes && mapping.frpNodes.length > 0) mapping.frpNodes.forEach((node)=>{
            result += "[".concat(node, "]");
        });
        if (mapping.listenPort) {
            if (mapping.frpNodes && mapping.frpNodes.length > 0) result += "[".concat(mapping.listenPort, "]");
            else result += mapping.listenPort;
        }
        if (mapping.targetPort) result += ":".concat(mapping.targetPort);
        if (mapping.protocol) result += "/".concat(mapping.protocol);
        return result;
    }
    renderWidget(section_id, _option_index, cfgvalue) {
        this.errorDivRefs = [];
        const current_values = Array.isArray(cfgvalue) ? cfgvalue : typeof cfgvalue === "string" ? String(cfgvalue).split(/\s+/).filter(Boolean) : [];
        const widget_id = this.cbid(section_id);
        const mappings_wrapper = /*#__PURE__*/ createJsxElement("div", {
            id: "portmapping-wrapper-".concat(section_id)
        });
        // 存储每个行的元素引用
        const rowRefs = [];
        const updateHiddenValue = ()=>{
            const values = [];
            for (const ref of rowRefs){
                const listen = ref.listenInput.value.trim();
                const target = ref.targetInput.value.trim();
                const protocol = ref.protocolSelect.value;
                const frpNodes = ref.getSelectedNodes();
                const temp = {
                    listenPort: listen,
                    targetPort: target,
                    frpNodes: frpNodes,
                    protocol: protocol
                };
                const str = this.buildString(temp);
                if (str && listen && target) values.push(str);
            }
            if (this.hiddenInput) this.hiddenInput.value = values.join(" ");
        };
        const renderMappingRow = (mapping_str, index)=>{
            const mapping = this.parseMapping(mapping_str) || {
                listenPort: "",
                targetPort: "",
                frpNodes: [],
                protocol: "tcp"
            };
            const row_id = "portmapping-row-".concat(section_id, "-").concat(index);
            let isTextMode = true;
            const listenInput = /*#__PURE__*/ createJsxElement(ValidatedInput, {
                type: "text",
                className: "listen-port-input",
                value: mapping.listenPort,
                placeholder: _("8080 or 8080-8090"),
                style: "width: 70px; min-width: 50px; margin-right: 10px;",
                dataAttributes: {
                    index: String(index),
                    section: section_id
                },
                onValidate: (value)=>{
                    if (!value.trim()) return false;
                    return this.validatePortOrRange(value.trim());
                }
            });
            const targetInput = /*#__PURE__*/ createJsxElement(ValidatedInput, {
                type: "text",
                className: "target-port-input",
                value: mapping.targetPort,
                placeholder: _("80 or 80-90"),
                style: "width: 70px; min-width: 50px; margin-right: 10px;",
                dataAttributes: {
                    index: String(index),
                    section: section_id
                },
                onValidate: (value)=>{
                    if (!value.trim()) return false;
                    return this.validatePortOrRange(value.trim());
                }
            });
            const protocolSelect = /*#__PURE__*/ createJsxElement("select", {
                class: "protocol-select",
                "data-index": index,
                "data-section": section_id,
                style: "width: 100px; margin-right: 10px;"
            }, /*#__PURE__*/ createJsxElement("option", {
                value: "tcp",
                selected: mapping.protocol === "tcp"
            }, "TCP"), /*#__PURE__*/ createJsxElement("option", {
                value: "udp",
                selected: mapping.protocol === "udp"
            }, "UDP"), /*#__PURE__*/ createJsxElement("option", {
                value: "both",
                selected: mapping.protocol === "both"
            }, "Both"));
            const textModeInput = /*#__PURE__*/ createJsxElement(ValidatedInput, {
                type: "text",
                className: "text-mode-input",
                value: mapping_str,
                placeholder: _("[8080][node1:9888]:80/tcp or 8080:80/tcp"),
                style: "width: 100%; margin-bottom: 6px; padding: 5px; display: none;",
                validateOn: "blur",
                onValidate: (value)=>{
                    const parsed = this.parseMapping(value);
                    return !!parsed;
                }
            });
            const previewDiv = /*#__PURE__*/ createJsxElement("div", {
                class: "portmapping-preview",
                "data-index": index,
                style: "margin-top: 6px; padding: 6px; background: #e8f4f8; border-left: 3px solid #0088cc; font-family: monospace; font-size: 12px;"
            }, _("Preview: "), this.buildString(mapping));
            const updatePreview = ()=>{
                const listen = listenInput.value.trim();
                const target = targetInput.value.trim();
                const protocol = protocolSelect.value;
                const frpNodes = getSelectedNodes();
                const temp_mapping = {
                    listenPort: listen,
                    targetPort: target,
                    frpNodes: frpNodes,
                    protocol: protocol
                };
                const preview_str = this.buildString(temp_mapping);
                previewDiv.textContent = _("Preview: ") + preview_str;
                textModeInput.value = preview_str;
            };
            // 使用复用的 FRP 节点选择器组件
            const selector = createFrpNodeSelector({
                selectedNodes: mapping.frpNodes || [],
                onChange: ()=>{
                    validateAndUpdate();
                },
                checkboxClass: "frp-node-checkbox-pm",
                portInputClass: "frp-node-port-pm"
            });
            const { container: selectorContainer, getSelectedNodes, isValid: isFrpValid, getValidationError: getFrpError } = selector;
            const frpContainer = /*#__PURE__*/ createJsxElement("div", {
                class: "frp-nodes-select",
                style: "display: block; margin-top: 6px;"
            }, /*#__PURE__*/ createJsxElement("span", {
                style: "display: block; margin-bottom: 6px; font-weight: bold;"
            }, _("FRP Nodes (Optional):")));
            frpContainer.appendChild(selectorContainer);
            const errorDiv = /*#__PURE__*/ createJsxElement("div", {
                class: "portmapping-error",
                "data-index": index,
                style: "color: red; margin-top: 6px; font-size: 12px; display: none;"
            });
            this.errorDivRefs.push(errorDiv);
            const titleRow = /*#__PURE__*/ createJsxElement("div", {
                style: "display: flex; gap: 10px; align-items: center;"
            }, /*#__PURE__*/ createJsxElement("span", {
                style: "min-width: 80px; font-weight: bold;"
            }, _("Listen Port:")), listenInput, /*#__PURE__*/ createJsxElement("span", {
                style: "min-width: 80px; font-weight: bold;"
            }, _("Target Port:")), targetInput, /*#__PURE__*/ createJsxElement("span", {
                style: "min-width: 60px; font-weight: bold;"
            }, _("Protocol:")), protocolSelect);
            const modeToggleBtn = /*#__PURE__*/ createJsxElement("button", {
                type: "button",
                class: "btn cbi-button cbi-button-edit",
                style: "margin-right: 8px;"
            }, _("Text Edit"));
            const deleteBtn = /*#__PURE__*/ createJsxElement("button", {
                type: "button",
                class: "btn cbi-button cbi-button-remove",
                "data-index": index,
                "data-section": section_id
            }, _("Delete"));
            const buttonRow = /*#__PURE__*/ createJsxElement("div", {
                style: "display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;"
            }, /*#__PURE__*/ createJsxElement("div", null, modeToggleBtn), /*#__PURE__*/ createJsxElement("div", null, deleteBtn));
            const row = /*#__PURE__*/ createJsxElement("div", {
                id: row_id,
                class: "portmapping-row",
                "data-index": index,
                style: "margin-bottom: 10px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; background: #f9f9f9;"
            }, buttonRow, titleRow, textModeInput, frpContainer, errorDiv, previewDiv);
            const validateAndUpdate = ()=>{
                const listen = listenInput.value.trim();
                const target = targetInput.value.trim();
                errorDiv.textContent = "";
                errorDiv.style.display = "none";
                let hasError = false;
                if (listen && !this.validatePortOrRange(listen)) {
                    errorDiv.textContent = _("Invalid listen port format");
                    errorDiv.style.display = "block";
                    hasError = true;
                }
                if (!hasError && target && !this.validatePortOrRange(target)) {
                    errorDiv.textContent = _("Invalid target port format");
                    errorDiv.style.display = "block";
                    hasError = true;
                }
                if (!hasError && listen && target) {
                    const listenPorts = this.parsePortRange(listen);
                    const targetPorts = this.parsePortRange(target);
                    if (listenPorts.length !== targetPorts.length) {
                        errorDiv.textContent = _("Port ranges must have the same size");
                        errorDiv.style.display = "block";
                        hasError = true;
                    }
                }
                if (!hasError && !isFrpValid()) {
                    errorDiv.textContent = getFrpError();
                    errorDiv.style.display = "block";
                    hasError = true;
                }
                if (!hasError) updatePreview();
                updateHiddenValue();
            };
            listenInput.oninput = validateAndUpdate;
            listenInput.onchange = validateAndUpdate;
            targetInput.oninput = validateAndUpdate;
            targetInput.onchange = validateAndUpdate;
            protocolSelect.onchange = validateAndUpdate;
            textModeInput.onblur = (ev)=>{
                const inputEl = ev.currentTarget;
                if (!inputEl) return;
                errorDiv.textContent = "";
                errorDiv.style.display = "none";
                const parsed = this.parseMapping(inputEl.value);
                if (parsed) {
                    const tempListenHandler = listenInput.oninput;
                    const tempTargetHandler = targetInput.oninput;
                    const tempProtocolHandler = protocolSelect.onchange;
                    listenInput.oninput = null;
                    targetInput.oninput = null;
                    protocolSelect.onchange = null;
                    listenInput.value = parsed.listenPort;
                    targetInput.value = parsed.targetPort;
                    protocolSelect.value = parsed.protocol;
                    listenInput.oninput = tempListenHandler;
                    targetInput.oninput = tempTargetHandler;
                    protocolSelect.onchange = tempProtocolHandler;
                    validateAndUpdate();
                } else {
                    errorDiv.textContent = _("Invalid port mapping format");
                    errorDiv.style.display = "block";
                }
            };
            function setDisplay(element, display) {
                element.style.setProperty("display", display, "important");
            }
            function updateVis() {
                setDisplay(titleRow, isTextMode ? "none" : "flex");
                setDisplay(frpContainer, isTextMode ? "none" : "block");
                setDisplay(textModeInput, isTextMode ? "block" : "none");
                setDisplay(previewDiv, isTextMode ? "none" : "block");
                modeToggleBtn.textContent = isTextMode ? _("Visual Edit") : _("Text Edit");
            }
            updateVis();
            modeToggleBtn.onclick = (e)=>{
                e.preventDefault();
                isTextMode = !isTextMode;
                updateVis();
            };
            deleteBtn.onclick = (e)=>{
                e.preventDefault();
                row.remove();
                // 从 rowRefs 中移除当前行的引用
                const idx = rowRefs.findIndex((ref)=>ref.listenInput === listenInput && ref.targetInput === targetInput && ref.protocolSelect === protocolSelect);
                if (idx !== -1) rowRefs.splice(idx, 1);
                updateHiddenValue();
            };
            return {
                element: row,
                listenInput,
                targetInput,
                protocolSelect,
                getSelectedNodes
            };
        };
        for(let i = 0; i < current_values.length; i++){
            const rowData = renderMappingRow(current_values[i], i);
            rowRefs.push(rowData);
            mappings_wrapper.appendChild(rowData.element);
        }
        const addBtn = /*#__PURE__*/ createJsxElement("button", {
            type: "button",
            class: "btn btn-sm btn-primary",
            style: "margin-bottom: 10px;"
        }, _("Add Port Mapping"));
        addBtn.onclick = (e)=>{
            e.preventDefault();
            const new_index = rowRefs.length;
            const rowData = renderMappingRow("", new_index);
            rowRefs.push(rowData);
            mappings_wrapper.appendChild(rowData.element);
        };
        const hiddenInput = /*#__PURE__*/ createJsxElement("input", {
            type: "hidden",
            name: widget_id,
            value: current_values.join(" ")
        });
        this.hiddenInput = hiddenInput;
        const container = /*#__PURE__*/ createJsxElement("div", {
            class: "cbi-value-field"
        }, mappings_wrapper, addBtn, hiddenInput, /*#__PURE__*/ createJsxElement("div", {
            class: "cbi-value-description"
        }, _("Configure port forwarding rules. Listen Port and Target Port support single port (8080) or port range (8080-8090).")));
        return container;
    }
    cfgvalue(section_id) {
        const value = L.uci.get("portweaver", section_id, "port_mapping");
        if (Array.isArray(value)) return value;
        if (typeof value === "string") return String(value).split(/\s+/).filter(Boolean);
        return [];
    }
    formvalue(section_id) {
        var _this_hiddenInput;
        if ((_this_hiddenInput = this.hiddenInput) === null || _this_hiddenInput === void 0 ? void 0 : _this_hiddenInput.value) return this.hiddenInput.value.split(/\s+/).filter(Boolean);
        return null;
    }
    write(section_id, formvalue) {
        if (formvalue && formvalue.length > 0) return L.uci.set("portweaver", section_id, "port_mapping", formvalue);
        else return L.uci.unset("portweaver", section_id, "port_mapping");
    }
    validate(section_id, value) {
        // 验证端口映射格式
        if (!value) {
            this.validationError = "";
            this.isValidFlag = true;
            return;
        }
        const valueStr = Array.isArray(value) ? value.join(" ") : String(value);
        const mappings = valueStr.split(/\s+/).filter(Boolean);
        for (const mappingStr of mappings){
            const parsed = this.parseMapping(mappingStr);
            if (!parsed) {
                this.validationError = _("Invalid port mapping format");
                this.isValidFlag = false;
                return;
            }
            // 验证监听端口
            if (!parsed.listenPort) {
                this.validationError = _("Listen port is required");
                this.isValidFlag = false;
                return;
            }
            if (!this.validatePortOrRange(parsed.listenPort)) {
                this.validationError = _("Invalid listen port format. Use port (8080) or range (8080-8090)");
                this.isValidFlag = false;
                return;
            }
            // 验证目标端口
            if (!parsed.targetPort) {
                this.validationError = _("Target port is required");
                this.isValidFlag = false;
                return;
            }
            if (!this.validatePortOrRange(parsed.targetPort)) {
                this.validationError = _("Invalid target port format. Use port (80) or range (80-90)");
                this.isValidFlag = false;
                return;
            }
            // 验证端口范围匹配
            const listenPorts = this.parsePortRange(parsed.listenPort);
            const targetPorts = this.parsePortRange(parsed.targetPort);
            if (listenPorts.length !== targetPorts.length) {
                this.validationError = _("Listen port range and target port range must have the same size");
                this.isValidFlag = false;
                return;
            }
            // 验证 FRP 节点
            if (parsed.frpNodes && parsed.frpNodes.length > 0) for (const nodeStr of parsed.frpNodes){
                const [node, port] = nodeStr.split(":");
                if (!node) {
                    this.validationError = _("Invalid FRP node format");
                    this.isValidFlag = false;
                    return;
                }
                if (port) {
                    const portNum = parseInt(port, 10);
                    if (Number.isNaN(portNum) || portNum < 1 || portNum > 65535) {
                        this.validationError = _("FRP node port must be between 1 and 65535");
                        this.isValidFlag = false;
                        return;
                    }
                }
            }
            // 验证协议
            if (parsed.protocol && ![
                "tcp",
                "udp",
                "both"
            ].includes(parsed.protocol)) {
                this.validationError = _("Protocol must be tcp, udp, or both");
                this.isValidFlag = false;
                return;
            }
        }
        this.validationError = "";
        this.isValidFlag = true;
    }
    validatePortOrRange(portStr) {
        // 验证单个端口或端口范围
        if (!portStr) return false;
        // 单个端口
        if (/^\d+$/.test(portStr)) {
            const port = parseInt(portStr, 10);
            return port >= 1 && port <= 65535;
        }
        // 端口范围
        if (/^\d+-\d+$/.test(portStr)) {
            const [start, end] = portStr.split("-").map((p)=>parseInt(p, 10));
            return start >= 1 && start <= 65535 && end >= 1 && end <= 65535 && start <= end;
        }
        return false;
    }
    parsePortRange(portStr) {
        // 解析端口或端口范围，返回端口数组
        if (/^\d+$/.test(portStr)) return [
            parseInt(portStr, 10)
        ];
        if (/^\d+-\d+$/.test(portStr)) {
            const [start, end] = portStr.split("-").map((p)=>parseInt(p, 10));
            const ports = [];
            for(let i = start; i <= end; i++)ports.push(i);
            return ports;
        }
        return [];
    }
    isValid(section_id) {
        var _this_isValidFlag;
        for (const errorEl of this.errorDivRefs){
            const isVisible = errorEl.style.display !== "none";
            const hasText = errorEl.textContent && errorEl.textContent.trim() !== "";
            if (isVisible && hasText) {
                this.validationError = errorEl.textContent || _("Validation failed");
                this.isValidFlag = false;
                return false;
            }
        }
        const value = this.formvalue(section_id);
        this.validate(section_id, value);
        return (_this_isValidFlag = this.isValidFlag) !== null && _this_isValidFlag !== void 0 ? _this_isValidFlag : true;
    }
    getValidationError(section_id) {
        if (!this.isValid(section_id)) return this.validationError || _("Validation failed");
        return "";
    }
    constructor(...args){
        super(...args), _define_property(this, "hiddenInput", void 0), _define_property(this, "errorDivRefs", []), _define_property(this, "validationError", ""), _define_property(this, "isValidFlag", true);
    }
}
/* export default */ const components_PortMappingEditor = (PortMappingEditor);

;// CONCATENATED MODULE: ./modules/config.tsx


const config_form = L.form;
const uci = L.uci;
/* export default */ function config(m, s, client, tab_id) {
    let o;
    o = s.taboption(tab_id, config_form.SectionValue, "_projects", config_form.GridSection, "project");
    const ss = o.subsection;
    ss.anonymous = true;
    ss.addremove = true;
    ss.sortable = true;
    ss.cloneable = true;
    ss.sectiontitle = (section_id)=>uci.get("portweaver", section_id, "remark") || _("Unnamed project");
    o = ss.option(config_form.DummyValue, "_runtime_status", _("Status"));
    o.modalonly = false;
    o.textvalue = (section_id)=>{
        const status = client.getProjectStatus(section_id);
        return /*#__PURE__*/ createJsxElement("div", {
            id: "project-status-".concat(section_id)
        }, client.renderStatusElements(status, section_id));
    };
    o = ss.option(config_form.Button, "_runtime_toggle", _("Toggle"));
    o.modalonly = false;
    o.editable = true;
    o.inputtitle = (section_id)=>{
        const status = client.getProjectStatus(section_id);
        return (status === null || status === void 0 ? void 0 : status.enabled) ? _("Disable") : _("Enable");
    };
    o.onclick = (_ev, section_id)=>window.portweaverToggle(section_id);
    o = ss.option(config_form.Flag, "enabled", _("Enabled"));
    o.modalonly = false;
    o.default = "1";
    o.editable = true;
    // Preview column
    o = ss.option(config_form.DummyValue, "_preview", _("Overview"));
    o.modalonly = false;
    o.textvalue = (section_id)=>{
        const protocol = uci.get("portweaver", section_id, "protocol") || "tcp";
        const family = uci.get("portweaver", section_id, "family") || "any";
        const listen_port = uci.get("portweaver", section_id, "listen_port") || "";
        const target_address = uci.get("portweaver", section_id, "target_address") || "";
        const target_port = uci.get("portweaver", section_id, "target_port") || "";
        const port_mappings = L.toArray(uci.get("portweaver", section_id, "port_mapping"));
        const src_zones = L.toArray(uci.get("portweaver", section_id, "src_zone"));
        const dest_zones = L.toArray(uci.get("portweaver", section_id, "dest_zone"));
        const proto_text = {
            both: _("TCP and UDP"),
            tcp: "TCP",
            udp: "UDP"
        }[protocol] || String(protocol).toUpperCase();
        const family_text = {
            any: _("IPv4 and IPv6"),
            ipv4: "IPv4",
            ipv6: "IPv6"
        }[family] || family;
        const lines = [];
        lines.push(/*#__PURE__*/ createJsxElement("span", null, _("Incoming "), /*#__PURE__*/ createJsxElement("var", null, family_text), _(" protocol "), /*#__PURE__*/ createJsxElement("var", null, proto_text)));
        if (src_zones.length > 0) {
            const src_badges = src_zones.map((z)=>/*#__PURE__*/ createJsxElement("span", {
                    class: "zonebadge",
                    style: fwmodel.getZoneColorStyle(z)
                }, /*#__PURE__*/ createJsxElement("strong", null, z || /*#__PURE__*/ createJsxElement("em", null, _("any zone")))));
            lines.push(/*#__PURE__*/ createJsxElement("br", null));
            lines.push(/*#__PURE__*/ createJsxElement("span", null, _("From "), ...src_badges));
        }
        if (port_mappings.length > 0) {
            lines.push(/*#__PURE__*/ createJsxElement("br", null));
            lines.push(/*#__PURE__*/ createJsxElement("span", null, /*#__PURE__*/ createJsxElement("strong", {
                style: "color: #09c;"
            }, _("Multi-Port")), _(" - "), /*#__PURE__*/ createJsxElement("var", null, port_mappings.length), _(" mapping(s)")));
            const first = port_mappings[0];
            lines.push(/*#__PURE__*/ createJsxElement("br", null));
            lines.push(/*#__PURE__*/ createJsxElement("span", null, _("e.g. "), /*#__PURE__*/ createJsxElement("var", null, first)));
        } else if (listen_port) {
            lines.push(/*#__PURE__*/ createJsxElement("br", null));
            lines.push(/*#__PURE__*/ createJsxElement("span", null, _("Port "), /*#__PURE__*/ createJsxElement("var", null, listen_port)));
        }
        lines.push(/*#__PURE__*/ createJsxElement("br", null));
        lines.push(/*#__PURE__*/ createJsxElement("span", null, /*#__PURE__*/ createJsxElement("var", {
            "data-tooltip": "Forward"
        }, _("Forward")), _(" to ")));
        if (dest_zones.length > 0) {
            const dest_badges = dest_zones.map((z)=>/*#__PURE__*/ createJsxElement("span", {
                    class: "zonebadge",
                    style: fwmodel.getZoneColorStyle(z)
                }, /*#__PURE__*/ createJsxElement("strong", null, z || /*#__PURE__*/ createJsxElement("em", null, _("any zone")))));
            lines.push(...dest_badges);
            lines.push(_(" "));
        }
        if (target_address) lines.push(/*#__PURE__*/ createJsxElement("span", null, _("IP "), /*#__PURE__*/ createJsxElement("var", null, target_address)));
        if (port_mappings.length === 0 && target_port) lines.push(/*#__PURE__*/ createJsxElement("span", null, _(" port "), /*#__PURE__*/ createJsxElement("var", null, target_port)));
        return /*#__PURE__*/ createJsxElement("small", null, lines);
    };
    // Modal configuration fields
    o = ss.option(config_form.Value, "remark", _("Remark"));
    o.modalonly = true;
    o.rmempty = false;
    o.datatype = "string";
    o.validate = (_section_id, value)=>{
        if (!value || String(value).trim() === "") return _("This field is required");
        return true;
    };
    o.placeholder = "My Project";
    o = ss.option(config_form.Flag, "enabled", _("Enabled"));
    o.modalonly = true;
    o.default = "1";
    o = ss.option(widgets.ZoneSelect, "src_zone", _("Source Zones"));
    o.modalonly = true;
    o.multiple = true;
    o.nocreate = false;
    o.allowlocal = false;
    o.default = "wan";
    o.rmempty = true;
    o = ss.option(widgets.ZoneSelect, "dest_zone", _("Destination Zones"));
    o.modalonly = true;
    o.multiple = true;
    o.nocreate = false;
    o.allowlocal = false;
    o.default = "lan";
    o.rmempty = true;
    o = ss.option(config_form.ListValue, "family", _("Address Family"));
    o.modalonly = true;
    o.value("any", _("IPv4 and IPv6"));
    o.value("ipv4", "IPv4");
    o.value("ipv6", "IPv6");
    o.default = "any";
    o = ss.option(config_form.Value, "target_address", _("Target Address"));
    o.modalonly = true;
    o.rmempty = false;
    o.datatype = "host";
    o.placeholder = "192.168.1.100";
    o.validate = (_section_id, value)=>{
        if (!value || String(value).trim() === "") return _("This field is required");
        return true;
    };
    // Port mode switcher
    o = ss.option(config_form.Flag, "use_port_mappings", _("Use Port Mappings Mode"));
    o.modalonly = true;
    o.rmempty = true;
    o.default = "0";
    o.description = _("Enable to configure multiple port mappings or port ranges. Disable for single port mode.");
    // Single port mode
    o = ss.option(config_form.ListValue, "protocol", _("Protocol"));
    o.modalonly = true;
    o.value("both", _("TCP and UDP"));
    o.value("tcp", "TCP");
    o.value("udp", "UDP");
    o.default = "tcp";
    o.depends("use_port_mappings", "0");
    // FRP node selector component factory
    o = ss.option(components_FrpNodeSelector, "frp_nodes", _("FRP Tunnels"));
    o.modalonly = true;
    o.rmempty = true;
    o.depends("use_port_mappings", "0");
    o.depends("enable_app_forward", "1");
    // Port Mapping Editor component factory
    o = ss.option(components_PortMappingEditor, "port_mapping", _("Port Mappings"));
    o.modalonly = true;
    o.depends("use_port_mappings", "1");
    o = ss.option(config_form.Value, "listen_port", _("Listen Port"));
    o.modalonly = true;
    o.datatype = "port";
    o.placeholder = "8080";
    o.depends("use_port_mappings", "0");
    o.validate = (section_id, value)=>{
        const use_mappings = uci.get("portweaver", section_id, "use_port_mappings");
        if (use_mappings !== "1") {
            if (!value || String(value).trim() === "") return _("This field is required in single port mode");
        }
        return true;
    };
    o = ss.option(config_form.Value, "target_port", _("Target Port"));
    o.modalonly = true;
    o.datatype = "port";
    o.placeholder = "80";
    o.depends("use_port_mappings", "0");
    o.validate = (section_id, value)=>{
        const use_mappings = uci.get("portweaver", section_id, "use_port_mappings");
        if (use_mappings !== "1") {
            if (!value || String(value).trim() === "") return _("This field is required in single port mode");
        }
        return true;
    };
    o = ss.option(config_form.Flag, "open_firewall_port", _("Open Firewall Port"));
    o.modalonly = true;
    o.default = "1";
    o = ss.option(config_form.Flag, "enable_app_forward", _("Enable App Level Forward"));
    o.modalonly = true;
    o.default = "0";
    o = ss.option(config_form.Flag, "reuseaddr", _("Reuse Address"));
    o.modalonly = true;
    o.default = "1";
    o.depends("enable_app_forward", "1");
    o = ss.option(config_form.Flag, "enable_stats", _("Enable Statistics"), _("Collect traffic statistics (bytes_in/bytes_out) using zero-cost atomic counters. NOTE: Mutually exclusive with firewall forwarding - enabling stats will disable add_firewall_forward."));
    o.modalonly = true;
    o.default = "0";
    o.depends("enable_app_forward", "1");
    o = ss.option(config_form.Flag, "add_firewall_forward", _("Add Firewall Forward"));
    o.modalonly = true;
    o.default = "1";
    o.depends({
        enable_app_forward: "0"
    });
    o.depends({
        enable_app_forward: "1",
        enable_stats: "0"
    });
}

;// CONCATENATED MODULE: ./components/StatusPanel.tsx

class StatusPanel {
    render(status, frpStatus, projectStatuses, events) {
        const statusColor = {
            running: "#28a745",
            stopped: "#dc3545",
            degraded: "#ffc107"
        }[status.status || ""] || "#6c757d";
        // Calculate project health stats
        const enabledProjects = (projectStatuses === null || projectStatuses === void 0 ? void 0 : projectStatuses.filter((p)=>p.enabled)) || [];
        const runningProjects = enabledProjects.filter((p)=>p.status === "running");
        const hasEnabledProjects = enabledProjects.length > 0;
        return /*#__PURE__*/ createJsxElement("div", null, /*#__PURE__*/ createJsxElement("div", {
            style: "display: grid; grid-template-columns: repeat(3, 1fr); gap: 1em; margin-top: 0.5em;"
        }, this.card(_("Status"), /*#__PURE__*/ createJsxElement("strong", {
            style: "color: ".concat(statusColor, "; font-size: 1.1em; font-weight: 600;"),
            id: "status-value"
        }, status.status || "-")), this.card(_("Total Projects"), /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600;",
            id: "total-projects-value"
        }, status.total_projects || 0)), this.card(_("Active Ports"), /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600;",
            id: "active-ports-value"
        }, status.active_ports || 0)), this.card(_("Uptime"), /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600;",
            id: "uptime-value"
        }, formatUptime(status.uptime || 0))), this.card(_("Traffic In"), /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600;",
            id: "traffic-in-value"
        }, formatBytes(status.total_bytes_in || 0))), this.card(_("Traffic Out"), /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600;",
            id: "traffic-out-value"
        }, formatBytes(status.total_bytes_out || 0))), hasEnabledProjects && this.card(_("Project Health"), /*#__PURE__*/ createJsxElement("div", {
            id: "project-health-value"
        }, /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600; color: ".concat(runningProjects.length === enabledProjects.length ? "#28a745" : runningProjects.length > 0 ? "#ffc107" : "#dc3545", ";")
        }, runningProjects.length, " / ", enabledProjects.length), /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.85em; color: #6c757d; margin-top: 0.3em;"
        }, _("projects running")))), frpStatus && this.card(_("FRP Status"), /*#__PURE__*/ createJsxElement("div", null, /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 1.1em; font-weight: 600; color: ".concat(this.getFrpStatusColor(frpStatus), ";"),
            id: "frp-enabled-value"
        }, this.getFrpStatusText(frpStatus)), frpStatus.frp_version && /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.85em; color: #6c757d; margin-top: 0.3em;",
            id: "frp-version-value"
        }, frpStatus.frp_version), frpStatus.client_count !== undefined && frpStatus.client_count > 0 && /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.85em; color: #6c757d; margin-top: 0.2em;"
        }, frpStatus.client_count, " ", _("client(s)")))), (frpStatus === null || frpStatus === void 0 ? void 0 : frpStatus.last_error) && this.card(_("FRP Error"), /*#__PURE__*/ createJsxElement("div", {
            style: "cursor: help;",
            title: frpStatus.last_error,
            id: "frp-error-value"
        }, /*#__PURE__*/ createJsxElement("strong", {
            style: "font-size: 0.95em; font-weight: 600; color: #dc3545;"
        }, this.truncateError(frpStatus.last_error, 50))))), events && events.length > 0 && this.renderActivityLog(events));
    }
    getFrpStatusColor(frpStatus) {
        if (!frpStatus.frp_enabled) return "#6c757d";
        switch(frpStatus.frp_status){
            case "connected":
                return "#28a745";
            case "connecting":
                return "#ffc107";
            case "error":
                return "#dc3545";
            case "stopped":
                return "#6c757d";
            default:
                return frpStatus.frp_enabled ? "#28a745" : "#6c757d";
        }
    }
    getFrpStatusText(frpStatus) {
        if (!frpStatus.frp_enabled) return _("Disabled");
        if (frpStatus.frp_status) switch(frpStatus.frp_status){
            case "connected":
                return _("Connected");
            case "connecting":
                return _("Connecting");
            case "error":
                return _("Error");
            case "stopped":
                return _("Stopped");
            default:
                return frpStatus.frp_status;
        }
        return _("Enabled");
    }
    truncateError(error, maxLen) {
        if (error.length <= maxLen) return error;
        return error.substring(0, maxLen - 3) + "...";
    }
    renderActivityLog(events) {
        // Show last 5 events, most recent first
        const recentEvents = events.slice(-5).reverse();
        return /*#__PURE__*/ createJsxElement("div", {
            style: "margin-top: 1em; border: 1px solid #dee2e6; border-radius: 4px; padding: 0.8em;"
        }, /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.9em; font-weight: 600; margin-bottom: 0.5em; color: #495057;"
        }, _("Recent Activity")), /*#__PURE__*/ createJsxElement("div", {
            style: "max-height: 150px; overflow-y: auto;",
            id: "activity-log-container"
        }, recentEvents.map((event)=>this.renderEventRow(event))));
    }
    renderEventRow(event) {
        const eventColors = {
            project_started: "#28a745",
            project_stopped: "#6c757d",
            frp_error: "#dc3545",
            frp_connected: "#28a745",
            frp_disconnected: "#ffc107",
            config_changed: "#17a2b8"
        };
        const eventIcons = {
            project_started: "\u25B6",
            project_stopped: "\u23F9",
            frp_error: "\u26A0",
            frp_connected: "\uD83D\uDD17",
            frp_disconnected: "\uD83D\uDD0C",
            config_changed: "\u2699"
        };
        const color = eventColors[event.type] || "#6c757d";
        const icon = eventIcons[event.type] || "\u2022";
        const time = this.formatTimestamp(event.timestamp);
        return /*#__PURE__*/ createJsxElement("div", {
            style: "display: flex; align-items: flex-start; padding: 0.3em 0; border-bottom: 1px solid #eee; font-size: 0.85em;"
        }, /*#__PURE__*/ createJsxElement("span", {
            style: "color: ".concat(color, "; margin-right: 0.5em; flex-shrink: 0;")
        }, icon), /*#__PURE__*/ createJsxElement("span", {
            style: "color: #6c757d; margin-right: 0.5em; flex-shrink: 0; min-width: 70px;"
        }, time), /*#__PURE__*/ createJsxElement("span", {
            style: "flex: 1; word-break: break-word;",
            title: event.message
        }, this.truncateError(event.message, 60)));
    }
    formatTimestamp(timestamp) {
        const date = new Date(timestamp);
        const hours = date.getHours().toString().padStart(2, "0");
        const minutes = date.getMinutes().toString().padStart(2, "0");
        const seconds = date.getSeconds().toString().padStart(2, "0");
        return "".concat(hours, ":").concat(minutes, ":").concat(seconds);
    }
    card(label, valueEl) {
        return /*#__PURE__*/ createJsxElement("div", {
            style: "border: 1px solid #dee2e6; padding: 0.8em; border-radius: 4px; background: transparent;"
        }, /*#__PURE__*/ createJsxElement("div", {
            style: "font-size: 0.85em; color: #6c757d; margin-bottom: 0.3em;"
        }, label), valueEl);
    }
}

;// CONCATENATED MODULE: ./modules/header.tsx

const header_form = L.form;

/* export default */ function header(m, s, client, tab_id) {
    let o;
    o = s.taboption(tab_id, header_form.Flag, "enabled", _("Enable PortWeaver"));
    o.default = "1";
    o.rmempty = false;
    o = s.taboption(tab_id, header_form.DummyValue, "_runtime_status", _("Runtime Status"));
    o.rawhtml = true;
    o.cfgvalue = ()=>{
        const panel = new StatusPanel();
        return panel.render(client.globalStatus, client.frpStatus, client.projectStatuses, client.events);
    };
    const runtimeToggle = async (section_id)=>{
        const idx = client.getProjectIndex(section_id);
        if (idx < 0) {
            L.ui.addNotification(null, /*#__PURE__*/ createJsxElement("p", null, _("Could not determine project index")), "error");
            return Promise.resolve();
        }
        const status = client.getProjectStatus(section_id);
        const newEnabled = !(status === null || status === void 0 ? void 0 : status.enabled);
        try {
            var _results_;
            await rpcClient.setEnabled(idx, !!newEnabled);
            L.ui.addNotification(null, /*#__PURE__*/ createJsxElement("p", null, _("Runtime state updated to: ") + (newEnabled ? _("enabled") : _("disabled"))), "info");
            const results = await Promise.all([
                rpcClient.getStatus(),
                rpcClient.listProjects()
            ]);
            client.globalStatus = results[0] || {};
            client.projectStatuses = ((_results_ = results[1]) === null || _results_ === void 0 ? void 0 : _results_.projects) ? results[1].projects : [];
            location.reload();
        } catch (err) {
            L.ui.addNotification(null, /*#__PURE__*/ createJsxElement("p", null, _("Failed to toggle runtime state: ") + ((err === null || err === void 0 ? void 0 : err.message) || String(err))), "error");
        }
    };
    window.portweaverToggle = runtimeToggle;
}

;// CONCATENATED MODULE: ./modules/logs.tsx
const logs_form = L.form;
const fs = L.fs;
L.uci;
const ui = L.ui;
const LOG_FILE = "/tmp/portweaver.log";
/* export default */ function logs(m, s, tab_id) {
    let o;
    o = s.taboption(tab_id, logs_form.Flag, "log_enabled", _("Enable Logging"));
    o.default = "1";
    o.rmempty = false;
    o.description = _("Enable logging output to /tmp/portweaver.log");
    o = s.taboption(tab_id, logs_form.DummyValue, "_logs_viewer");
    o.rawhtml = true;
    let pollInterval = null;
    const updateLogs = ()=>{
        const container = document.getElementById("portweaver-log-container");
        if (!container) return;
        fs.read_direct(LOG_FILE, "text").then((res)=>{
            container.textContent = res.trim() || _("Log is empty.");
        }).catch((err)=>{
            if (err.toString().includes("NotFoundError")) container.textContent = _("Log file does not exist.");
            else container.textContent = _("Error reading log: %s").format(err.toString());
        });
    };
    const clearLogs = async ()=>{
        if (!confirm(_("Are you sure you want to clear all logs?"))) return;
        try {
            await fs.write(LOG_FILE, "");
            ui.addNotification(null, E("p", _("Logs cleared successfully")), "info");
            updateLogs();
        } catch (err) {
            ui.addNotification(null, E("p", _("Failed to clear logs")), "error");
        }
    };
    const restartService = async ()=>{
        if (!confirm(_("Are you sure you want to restart PortWeaver service?"))) return;
        try {
            await fs.exec("/etc/init.d/portweaver", [
                "restart"
            ]);
            ui.addNotification(null, E("p", _("Service restarted successfully")), "info");
            setTimeout(updateLogs, 2000);
        } catch (err) {
            ui.addNotification(null, E("p", _("Failed to restart service")), "error");
        }
    };
    o.render = function() {
        if (pollInterval) clearInterval(pollInterval);
        pollInterval = setInterval(updateLogs, 3000);
        setTimeout(updateLogs, 100);
        return E("div", {
            class: "cbi-section"
        }, [
            E("div", {
                style: "display: flex; gap: 10px; margin-bottom: 10px; align-items: center;"
            }, [
                E("button", {
                    class: "btn cbi-button cbi-button-action",
                    click: updateLogs
                }, [
                    _("Refresh")
                ]),
                E("button", {
                    class: "btn cbi-button cbi-button-remove",
                    click: clearLogs
                }, [
                    _("Clear logs")
                ]),
                E("button", {
                    class: "btn cbi-button cbi-button-apply",
                    click: restartService
                }, [
                    _("Restart service")
                ]),
                E("small", {
                    style: "color: #666; margin-left: auto;"
                }, _("Auto-refresh every 3 seconds"))
            ]),
            E("pre", {
                id: "portweaver-log-container",
                style: "padding: 10px; background: #f5f5f5; border: 1px solid #ddd; font-family: monospace; white-space: pre-wrap; word-break: break-all; max-height: 400px; overflow-y: auto; margin: 0;"
            }, [
                _("Loading logs...")
            ])
        ]);
    };
}

;// CONCATENATED MODULE: ./main.tsx






const main_form = L.form;
const main_uci = L.uci;
class main extends L.view {
    async load() {
        return Promise.all([
            main_uci.load("portweaver"),
            main_uci.load("firewall"),
            rpcClient.getStatus().then((res)=>res || {}).catch((err)=>{
                console.warn("ubus get_status failed:", err);
                return {};
            }),
            rpcClient.listProjects().then((res)=>res || {
                    projects: []
                }).catch((err)=>{
                console.warn("ubus list_projects failed:", err);
                return {
                    projects: []
                };
            }),
            rpcClient.getFrpStatus().then((res)=>res || {
                    frp_enabled: false
                }).catch((err)=>{
                console.warn("ubus get_frp_status failed:", err);
                return {
                    frp_enabled: false
                };
            }),
            rpcClient.getEvents().then((res)=>(res === null || res === void 0 ? void 0 : res.events) || []).catch((err)=>{
                console.warn("ubus get_events failed:", err);
                return [];
            })
        ]);
    }
    render(data) {
        const m = new main_form.Map("portweaver", _("PortWeaver"), _("Port forwarding and NAT traversal configuration"));
        const s = m.section(main_form.NamedSection, "global", "portweaver");
        s.anonymous = true;
        s.addremove = false;
        s.tab("settings", _("Global Settings"));
        s.tab("projects", _("Port Forwarding"));
        s.tab("logs", _("System Logs"));
        s.tab("frp", _("FRP Tunnels"));
        const client = new Client([
            data[2],
            data[3],
            data[4],
            data[5]
        ]);
        header(m, s, client, "settings");
        config(m, s, client, "projects");
        logs(m, s, "logs");
        frp(m, s, "frp");
        return m.render();
    }
}


return main;