include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for PortWeaver
LUCI_DEPENDS:=+portweaver +luci-base
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-portweaver
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_LICENSE:=MIT
PKG_MAINTAINER:=LazuliKao

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
